<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="ReadCredentialsFromFile" targetNamespace="http://ReadCredentialsFromFile" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://ReadCredentialsFromFile" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="ReadCredentialsFromFileHttpBinding" originalBindingStyle="document"/>
        <generatedXSD location="ReadCredentialsFromFile_InlineSchema1.xsd"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  
  <wsdl:types>
    
        <xsd:schema targetNamespace="http://ReadCredentialsFromFile" xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
      <xsd:include schemaLocation="ReadCredentialsFromFile_InlineSchema1.xsd"/>
    </xsd:schema>
    </wsdl:types>
  <wsdl:message name="AuthenticationRequestMsg">
    <wsdl:part element="tns:Authentication" name="AuthenticationParameters"/>
  </wsdl:message>
  <wsdl:message name="AuthenticationResponseMsg">
    <wsdl:part element="tns:AuthenticationResponse" name="AuthenticationResult"/>
  </wsdl:message>
    <wsdl:portType name="ReadCredentialsFromFile">
    <wsdl:operation name="Authentication">
            <wsdl:input message="tns:AuthenticationRequestMsg" name="AuthenticationRequest"/>
            <wsdl:output message="tns:AuthenticationResponseMsg" name="AuthenticationResponse"/>
    </wsdl:operation>
    </wsdl:portType>
  <wsdl:binding name="ReadCredentialsFromFileHttpBinding" type="tns:ReadCredentialsFromFile">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="Authentication">
      <soap:operation soapAction="http://ReadCredentialsFromFile/Authentication"/>
      <wsdl:input name="AuthenticationRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="AuthenticationResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    </wsdl:binding>
  <wsdl:service name="ReadCredentialsFromFileHttpService">
    <wsdl:port binding="tns:ReadCredentialsFromFileHttpBinding" name="ReadCredentialsFromFileHttpPort">
      <soap:address location="http://localhost:7800/ReadCredentialsFromFile"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>